// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaYjiuUTi7DRTdOTS4U8xk3kzCgxXh9tQ',
    appId: '1:332637885308:web:222f7a9041065616c30af9',
    messagingSenderId: '332637885308',
    projectId: 'top-up-shops-4bd5b',
    authDomain: 'top-up-shops-4bd5b.firebaseapp.com',
    storageBucket: 'top-up-shops-4bd5b.firebasestorage.app',
    measurementId: 'G-757K3EQ80W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUv6DavXR-bYaWRr2nI2HfHyZBngeDwD8',
    appId: '1:332637885308:android:9741b46b9b38363ac30af9',
    messagingSenderId: '332637885308',
    projectId: 'top-up-shops-4bd5b',
    storageBucket: 'top-up-shops-4bd5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpLZ0v_yZMeD9XYQ_4FTuLJLYSdXL-Ag',
    appId: '1:332637885308:ios:5bbd5fb337ea45d6c30af9',
    messagingSenderId: '332637885308',
    projectId: 'top-up-shops-4bd5b',
    storageBucket: 'top-up-shops-4bd5b.firebasestorage.app',
    iosBundleId: 'com.example.topUpShops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaYjiuUTi7DRTdOTS4U8xk3kzCgxXh9tQ',
    appId: '1:332637885308:web:bb98e1693c68129bc30af9',
    messagingSenderId: '332637885308',
    projectId: 'top-up-shops-4bd5b',
    authDomain: 'top-up-shops-4bd5b.firebaseapp.com',
    storageBucket: 'top-up-shops-4bd5b.firebasestorage.app',
    measurementId: 'G-HJTK0KPR2E',
  );
}
